const thapaserialnoc = {
  id: "thapaserialnoc",
  name: "fox",
  company: "russion",
  price: 702899,
  colors: ["#22D3EF", "#CDD0D0"],
  description:
    "this is best pet for the purchase most populor and rated good height & wegiht any animal kept by human beings as a source of companionship and pleasure. While a pet is generally kept for the pleasure that it can give to its owner, often, especially with horses, dogs, and cats, as well as with some other domesticated animals, this pleasure appears to be mutual..",
  category: "laptop",
  stock: 12,
  reviews: 28,
  stars: 4.2,
  image: [
    {
      id: "randomid1",
      width: 1080,
      height: 650,
      url: "https://thumbs.dreamstime.com/z/red-fox-19304038.jpg",
      filename: "prod-1.png",
      size: 1080,
      type: "image/png",
    },
    {
      id: "randomid2",
      width: 1080,
      height: 650,
      url: " https://thumbs.dreamstime.com/z/red-fox-close-up-portrait-36119658.jpg",
      filename: "prod-2.png",
      size: 1080,
      type: "image/png",
    },
    {
      id: "randomid3",
      width: 1080,
      height: 650,
      url: " https://thumbs.dreamstime.com/z/young-fox-cub-standing-sunshine-looking-forwards-31009358.jpg",
      filename: "prod-3.png",
      size: 1080,
      type: "image/png",
    },
    {
      id: "randomid4",
      width: 1080,
      height: 650,
      url: "https://thumbs.dreamstime.com/z/fox-eating-28294113.jpg",
      filename: "prod-4.png",
      size: 1080,
      type: "image/png",
    },
  ],
};
const thapaserialnob = {
  id: "thapaserialnob",
  name: "samsung s20",
  company: "african",
  price: 500000,
  colors: ["#000", "#22D3EF"],
  description:
    "this is best pet for the purchase most populor and rated good height & wegiht any animal kept by human beings as a source of companionship and pleasure. While a pet is generally kept for the pleasure that it can give to its owner, often, especially with horses, dogs, and cats, as well as with some other domesticated animals, this pleasure appears to be mutual..",
  category: "cat",
  shipping: true,
  stock: 10,
  reviews: 28,
  stars: 4.4,
  image: [
    {
      id: "randomid1",
      width: 1080,
      height: 650,
      url: " https://thumbs.dreamstime.com/b/pet-cat-green-cats-eyes-gray-big-102425920.jpg",
      filename: "prod-1.png",
      size: 1080,
      type: "image/png",
    },
    {
      id: "randomid2",
      width: 1080,
      height: 650,
      url: " https://thumbs.dreamstime.com/b/cat-laughing-very-happy-54680614.jpg",
      filename: "prod-2.png",
      size: 1080,
      type: "image/png",
    },
    {
      id: "randomid3",
      width: 1080,
      height: 650,
      url: " https://thumbs.dreamstime.com/b/cat-lying-floor-37057229.jpg",
      filename: "prod-3.png",
      size: 1080,
      type: "image/png",
    },
    {
      id: "randomid4",
      width: 1080,
      height: 650,
      url: "https://thumbs.dreamstime.com/b/crossbreed-siberian-cat-persian-cat-6610485.jpg",
      filename: "prod-4.png",
      size: 1080,
      type: "image/png",
    },
  ],
};
const thapaserialnod = {
  id: "thapaserialnod",
  name: "Nokia 420",
  company: "desi",
  price: 102999,
  colors: ["#000000", "#CDD0D0"],
  description:
    "this is best pet for the purchase most populor and rated good height & wegiht any animal kept by human beings as a source of companionship and pleasure. While a pet is generally kept for the pleasure that it can give to its owner, often, especially with horses, dogs, and cats, as well as with some other domesticated animals, this pleasure appears to be mutual..",
  category: "dog",
  shipping: true,
  stock: 6,
  reviews: 28,
  stars: 3.8,
  image: [
    {
      id: "randomid1",
      width: 1080,
      height: 650,
      url: "https://thumbs.dreamstime.com/b/dog-listening-big-ear-27392035.jpg",
      filename: "prod-1.png",
      size: 1080,
      type: "image/png",
    },
    {
      id: "randomid2",
      width: 1080,
      height: 650,
      url: " https://thumbs.dreamstime.com/b/golden-retriever-dog-sitting-white-24750790.jpg",
      filename: "prod-2.png",
      size: 1080,
      type: "image/png",
    },
    {
      id: "randomid3",
      width: 1080,
      height: 650,
      url: " https://thumbs.dreamstime.com/b/computer-dog-clever-glasses-uses-43558625.jpg",
      filename: "prod-3.png",
      size: 1080,
      type: "image/png",
    },
    {
      id: "randomid4",
      width: 1080,
      height: 650,
      url: "https://thumbs.dreamstime.com/b/dog-love-rose-valentines-jack-russell-sticking-out-tongue-lying-bed-full-petals-as-background-day-wearing-78523443.jpg",
      filename: "prod-4.png",
      size: 1080,
      type: "image/png",
    },
  ],
};
const thapaserialnoe = {
  id: "thapaserialnoe",
  name: "Mac Pc",
  company:"jangli",
  price: 200999,
  colors: ["#000", "#CDD0D0"],
  description:
    "this is best pet for the purchase most populor and rated good height & wegiht any animal kept by human beings as a source of companionship and pleasure. While a pet is generally kept for the pleasure that it can give to its owner, often, especially with horses, dogs, and cats, as well as with some other domesticated animals, this pleasure appears to be mutual.",
  category: "lion",
  shipping: true,
  stock: 4,
  reviews: 28,
  stars: 2.8,
  image: [
    {
      id: "randomid1",
      width: 1080,
      height: 650,
      url: "https://thumbs.dreamstime.com/b/lion-portrait-savanna-landscape-background-mount-kilimanjaro-sunset-33764722.jpg",
      filename: "prod-1.png",
      size: 1080,
      type: "image/png",
    },
    {
      id: "randomid2",
      width: 1080,
      height: 650,
      url: " https://thumbs.dreamstime.com/b/majestic-lion-21664896.jpg",
      filename: "prod-2.png",
      size: 1080,
      type: "image/png",
    },
    {
      id: "randomid3",
      width: 1080,
      height: 650,
      url: " https://thumbs.dreamstime.com/b/angry-lion-roaring-against-stormy-sky-32089422.jpg",
      filename: "prod-3.png",
      size: 1080,
      type: "image/png",
    },
    {
      id: "randomid4",
      width: 1080,
      height: 650,
      url: "https://thumbs.dreamstime.com/b/beautiful-lion-romeo-ii-black-white-image-masai-mara-kenya-49186636.jpg",
      filename: "prod-4.png",
      size: 1080,
      type: "image/png",
    },
  ],
};
export { thapaserialnoc, thapaserialnob,thapaserialnod, thapaserialnoe };
